DROP TABLE WEBSITE_COUPONS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPONS
(
  ID                      NUMBER,
  CODE                    VARCHAR2(50 BYTE),
  AMOUNT                  NUMBER(10,2),
  DATE_CREATED            DATE,
  DATE_CREATED_GMT        DATE,
  DATE_MODIFIED           DATE,
  DATE_MODIFIED_GMT       DATE,
  DISCOUNT_TYPE           VARCHAR2(50 BYTE),
  DESCRIPTION             VARCHAR2(255 BYTE),
  DATE_EXPIRES            DATE,
  DATE_EXPIRES_GMT        DATE,
  USAGE_COUNT             NUMBER,
  INDIVIDUAL_USE          NUMBER(1),
  USAGE_LIMIT             NUMBER,
  USAGE_LIMIT_PER_USER    NUMBER,
  LIMIT_USAGE_TO_X_ITEMS  NUMBER,
  FREE_SHIPPING           NUMBER(1),
  EXCLUDE_SALE_ITEMS      NUMBER(1),
  MINIMUM_AMOUNT          NUMBER(10,2),
  MAXIMUM_AMOUNT          NUMBER(10,2)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE WEBSITE_COUPONS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE APEX_23321186687074315
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP TABLE WEBSITE_COUPON_EMAIL_RESTRICTIONS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPON_EMAIL_RESTRICTIONS
(
  COUPON_ID          NUMBER,
  EMAIL_RESTRICTION  VARCHAR2(255 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_COUPON_EXCLUDED_PRODUCT_CATEGORIES CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPON_EXCLUDED_PRODUCT_CATEGORIES
(
  COUPON_ID                     NUMBER,
  EXCLUDED_PRODUCT_CATEGORY_ID  NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_COUPON_EXCLUDED_PRODUCT_IDS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPON_EXCLUDED_PRODUCT_IDS
(
  COUPON_ID            NUMBER,
  EXCLUDED_PRODUCT_ID  NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_COUPON_PRODUCT_CATEGORIES CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPON_PRODUCT_CATEGORIES
(
  COUPON_ID            NUMBER,
  PRODUCT_CATEGORY_ID  NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_COUPON_PRODUCT_IDS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPON_PRODUCT_IDS
(
  COUPON_ID   NUMBER,
  PRODUCT_ID  NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_COUPON_USED_BY CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_COUPON_USED_BY
(
  COUPON_ID      NUMBER,
  USED_BY_EMAIL  VARCHAR2(255 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_CUSTOMERS
(
  ID                  NUMBER,
  DATE_CREATED        DATE,
  DATE_CREATED_GMT    DATE,
  DATE_MODIFIED       DATE,
  DATE_MODIFIED_GMT   DATE,
  EMAIL               VARCHAR2(255 BYTE),
  FIRST_NAME          VARCHAR2(255 BYTE),
  LAST_NAME           VARCHAR2(255 BYTE),
  ROLE                VARCHAR2(50 BYTE),
  USERNAME            VARCHAR2(50 BYTE),
  IS_PAYING_CUSTOMER  NUMBER(1),
  AVATAR_URL          VARCHAR2(255 BYTE),
  CUSTOMER_JSON       CLOB
)
LOB (CUSTOMER_JSON) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WEBSITE_CUSTOMERS_PK ON WEBSITE_CUSTOMERS
(ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WEBSITE_CUSTOMERS ADD (
  CONSTRAINT WEBSITE_CUSTOMERS_PK
  PRIMARY KEY
  (ID)
  USING INDEX WEBSITE_CUSTOMERS_PK
  ENABLE VALIDATE);


DROP TABLE WEBSITE_CUSTOMER_ADDRESS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_CUSTOMER_ADDRESS
(
  ID              NUMBER,
  ADDRESS_TYPE    VARCHAR2(100 BYTE),
  CUSTOMER_ID     NUMBER,
  INVOICE_NO      VARCHAR2(100 BYTE),
  FIRST_NAME      VARCHAR2(100 BYTE),
  LAST_NAME       VARCHAR2(100 BYTE),
  STREET_ADDRESS  VARCHAR2(1000 BYTE),
  APARTMENT       VARCHAR2(1000 BYTE),
  TOWN_CITY       VARCHAR2(100 BYTE),
  COUNTRY_REGION  VARCHAR2(100 BYTE),
  STATE_COUNTY    VARCHAR2(100 BYTE),
  POSTCODE_ZIP    VARCHAR2(100 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_ORDERS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_ORDERS
(
  ID                    NUMBER,
  PARENT_ID             NUMBER,
  NUM_BER               VARCHAR2(50 BYTE),
  ORDER_KEY             VARCHAR2(255 BYTE),
  CREATED_VIA           VARCHAR2(50 BYTE),
  VERSION               VARCHAR2(50 BYTE),
  STATUS                VARCHAR2(50 BYTE),
  CURRENCY              VARCHAR2(10 BYTE),
  DATE_CREATED          DATE,
  DATE_CREATED_GMT      DATE,
  DATE_MODIFIED         DATE,
  DATE_MODIFIED_GMT     DATE,
  DISCOUNT_TOTAL        NUMBER(10,2),
  DISCOUNT_TAX          NUMBER(10,2),
  SHIPPING_TOTAL        NUMBER(10,2),
  SHIPPING_TAX          NUMBER(10,2),
  CART_TAX              NUMBER(10,2),
  TOTAL                 NUMBER(10,2),
  TOTAL_TAX             NUMBER(10,2),
  PRICES_INCLUDE_TAX    NUMBER(1),
  CUSTOMER_ID           NUMBER,
  CUSTOMER_IP_ADDRESS   VARCHAR2(50 BYTE),
  CUSTOMER_USER_AGENT   VARCHAR2(255 BYTE),
  CUSTOMER_NOTE         CLOB,
  PAYMENT_METHOD        VARCHAR2(50 BYTE),
  PAYMENT_METHOD_TITLE  VARCHAR2(255 BYTE),
  TRANSACTION_ID        VARCHAR2(255 BYTE),
  DATE_PAID             DATE,
  DATE_PAID_GMT         DATE,
  DATE_COMPLETED        DATE,
  DATE_COMPLETED_GMT    DATE,
  CART_HASH             VARCHAR2(255 BYTE),
  ORDER_JSON            CLOB
)
LOB (CUSTOMER_NOTE) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (ORDER_JSON) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE WEBSITE_ORDERS ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE APEX_23321186687074315
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP TABLE WEBSITE_ORDER_META_DATA CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_ORDER_META_DATA
(
  ORDER_ID    NUMBER,
  META_ID     NUMBER,
  META_KEY    VARCHAR2(255 BYTE),
  META_VALUE  VARCHAR2(255 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_PRODUCT_CATEGORIES CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_PRODUCT_CATEGORIES
(
  ID    NUMBER,
  NAME  VARCHAR2(255 BYTE),
  SLUG  VARCHAR2(255 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WEBSITE_PRODUCT_CATEGORIES_PK ON WEBSITE_PRODUCT_CATEGORIES
(ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WEBSITE_PRODUCT_CATEGORIES ADD (
  CONSTRAINT WEBSITE_PRODUCT_CATEGORIES_PK
  PRIMARY KEY
  (ID)
  USING INDEX WEBSITE_PRODUCT_CATEGORIES_PK
  ENABLE VALIDATE);


DROP TABLE WEBSITE_SHIPPING_ADDRESS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_SHIPPING_ADDRESS
(
  ID           NUMBER,
  CUSTOMER_ID  NUMBER,
  INVOICE_NO   VARCHAR2(20 BYTE),
  FIRST_NAME   VARCHAR2(255 BYTE),
  LAST_NAME    VARCHAR2(255 BYTE),
  COMPANY      VARCHAR2(255 BYTE),
  ADDRESS_1    VARCHAR2(255 BYTE),
  ADDRESS_2    VARCHAR2(255 BYTE),
  CITY         VARCHAR2(255 BYTE),
  STATE        VARCHAR2(50 BYTE),
  POSTCODE     VARCHAR2(20 BYTE),
  COUNTRY      VARCHAR2(50 BYTE),
  ORDER_ID     NUMBER,
  PHONE        VARCHAR2(100 BYTE),
  EMAIL        VARCHAR2(100 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WEBSITE_SHIPPING_ADDRESS_PK ON WEBSITE_SHIPPING_ADDRESS
(ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WEBSITE_SHIPPING_ADDRESS ADD (
  CONSTRAINT WEBSITE_SHIPPING_ADDRESS_PK
  PRIMARY KEY
  (ID)
  USING INDEX WEBSITE_SHIPPING_ADDRESS_PK
  ENABLE VALIDATE);


DROP TABLE WEBSITE_SHIPPING_LINES CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_SHIPPING_LINES
(
  ORDER_ID      NUMBER,
  LINE_ID       NUMBER,
  METHOD_TITLE  VARCHAR2(255 BYTE),
  METHOD_ID     VARCHAR2(50 BYTE),
  TOTAL         NUMBER(10,2),
  TOTAL_TAX     NUMBER(10,2)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_TAXES CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_TAXES
(
  ORDER_ID            NUMBER,
  TAX_ID              NUMBER,
  RATE_CODE           VARCHAR2(50 BYTE),
  RATE_ID             NUMBER,
  LABEL               VARCHAR2(255 BYTE),
  COMPOUND            NUMBER(1),
  TAX_TOTAL           NUMBER(10,2),
  SHIPPING_TAX_TOTAL  NUMBER(10,2)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


--  There is no statement for index SYS_C0043646.
--  The object is created when the parent object is created.

--  There is no statement for index SYS_C0043663.
--  The object is created when the parent object is created.

DROP TABLE WEBSITE_BILLING_ADDRESS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_BILLING_ADDRESS
(
  ID           NUMBER,
  INVOICE_NO   VARCHAR2(20 BYTE),
  CUSTOMER_ID  NUMBER,
  FIRST_NAME   VARCHAR2(255 BYTE),
  LAST_NAME    VARCHAR2(255 BYTE),
  COMPANY      VARCHAR2(255 BYTE),
  ADDRESS_1    VARCHAR2(255 BYTE),
  ADDRESS_2    VARCHAR2(255 BYTE),
  CITY         VARCHAR2(255 BYTE),
  STATE        VARCHAR2(50 BYTE),
  POSTCODE     VARCHAR2(20 BYTE),
  COUNTRY      VARCHAR2(50 BYTE),
  EMAIL        VARCHAR2(255 BYTE),
  PHONE        VARCHAR2(20 BYTE),
  ORDER_ID     NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WEBSITE_BILLING_ADDRESS_PK ON WEBSITE_BILLING_ADDRESS
(ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WEBSITE_BILLING_ADDRESS ADD (
  CONSTRAINT WEBSITE_BILLING_ADDRESS_PK
  PRIMARY KEY
  (ID)
  USING INDEX WEBSITE_BILLING_ADDRESS_PK
  ENABLE VALIDATE);


DROP TABLE WEBSITE_LINE_ITEMS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_LINE_ITEMS
(
  ORDER_ID      NUMBER,
  ITEM_ID       NUMBER,
  NAME          VARCHAR2(255 BYTE),
  PRODUCT_ID    NUMBER,
  VARIATION_ID  NUMBER,
  QUANTITY      NUMBER,
  TAX_CLASS     VARCHAR2(50 BYTE),
  SUBTOTAL      NUMBER(10,2),
  SUBTOTAL_TAX  NUMBER(10,2),
  TOTAL         NUMBER(10,2),
  TOTAL_TAX     NUMBER(10,2),
  SKU           VARCHAR2(50 BYTE),
  PRICE         NUMBER(10,2)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE WEBSITE_PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_PRODUCTS
(
  ID                     NUMBER,
  NAME                   VARCHAR2(255 BYTE),
  SLUG                   VARCHAR2(255 BYTE),
  PERMALINK              VARCHAR2(255 BYTE),
  DATE_CREATED           DATE,
  DATE_CREATED_GMT       DATE,
  DATE_MODIFIED          DATE,
  DATE_MODIFIED_GMT      DATE,
  TYPE                   VARCHAR2(50 BYTE),
  STATUS                 VARCHAR2(50 BYTE),
  FEATURED               NUMBER(1),
  CATALOG_VISIBILITY     VARCHAR2(50 BYTE),
  DESCRIPTION            CLOB,
  SHORT_DESCRIPTION      CLOB,
  SKU                    VARCHAR2(50 BYTE),
  PRICE                  NUMBER(10,2),
  REGULAR_PRICE          NUMBER(10,2),
  SALE_PRICE             NUMBER(10,2),
  DATE_ON_SALE_FROM      DATE,
  DATE_ON_SALE_FROM_GMT  DATE,
  DATE_ON_SALE_TO        DATE,
  DATE_ON_SALE_TO_GMT    DATE,
  PRICE_HTML             VARCHAR2(255 BYTE),
  ON_SALE                NUMBER(1),
  PURCHASABLE            NUMBER(1),
  TOTAL_SALES            NUMBER,
  VIRTUAL                NUMBER(1),
  DOWNLOADABLE           NUMBER(1),
  DOWNLOAD_LIMIT         NUMBER,
  DOWNLOAD_EXPIRY        NUMBER,
  EXTERNAL_URL           VARCHAR2(255 BYTE),
  BUTTON_TEXT            VARCHAR2(255 BYTE),
  TAX_STATUS             VARCHAR2(50 BYTE),
  TAX_CLASS              VARCHAR2(50 BYTE),
  MANAGE_STOCK           NUMBER(1),
  STOCK_QUANTITY         NUMBER,
  STOCK_STATUS           VARCHAR2(50 BYTE),
  BACKORDERS             VARCHAR2(50 BYTE),
  BACKORDERS_ALLOWED     NUMBER(1),
  BACKORDERED            NUMBER(1),
  SOLD_INDIVIDUALLY      NUMBER(1),
  WEIGHT                 VARCHAR2(50 BYTE),
  SHIPPING_REQUIRED      NUMBER(1),
  SHIPPING_TAXABLE       NUMBER(1),
  SHIPPING_CLASS         VARCHAR2(50 BYTE),
  SHIPPING_CLASS_ID      NUMBER,
  REVIEWS_ALLOWED        NUMBER(1),
  AVERAGE_RATING         NUMBER(3,2),
  RATING_COUNT           NUMBER,
  PARENT_ID              NUMBER,
  PURCHASE_NOTE          CLOB,
  MENU_ORDER             NUMBER,
  CATEGORY_ID            NUMBER,
  PRODUCT_JSON           CLOB
)
LOB (DESCRIPTION) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (PRODUCT_JSON) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (PURCHASE_NOTE) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (SHORT_DESCRIPTION) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WEBSITE_PRODUCTS_PK ON WEBSITE_PRODUCTS
(ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WEBSITE_PRODUCTS ADD (
  CONSTRAINT WEBSITE_PRODUCTS_PK
  PRIMARY KEY
  (ID)
  USING INDEX WEBSITE_PRODUCTS_PK
  ENABLE VALIDATE);


DROP TABLE WEBSITE_PRODUCT_IMAGES CASCADE CONSTRAINTS;

CREATE TABLE WEBSITE_PRODUCT_IMAGES
(
  ID                 NUMBER,
  PRODUCT_ID         NUMBER,
  DATE_CREATED       DATE,
  DATE_CREATED_GMT   DATE,
  DATE_MODIFIED      DATE,
  DATE_MODIFIED_GMT  DATE,
  SRC                VARCHAR2(255 BYTE),
  NAME               VARCHAR2(255 BYTE),
  ALT                VARCHAR2(255 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX WEBSITE_PRODUCT_IMAGES_PK ON WEBSITE_PRODUCT_IMAGES
(ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE WEBSITE_PRODUCT_IMAGES ADD (
  CONSTRAINT WEBSITE_PRODUCT_IMAGES_PK
  PRIMARY KEY
  (ID)
  USING INDEX WEBSITE_PRODUCT_IMAGES_PK
  ENABLE VALIDATE);


ALTER TABLE WEBSITE_COUPON_EMAIL_RESTRICTIONS ADD (
  CONSTRAINT FK_COUPON_EMAIL_RESTRICTIONS 
  FOREIGN KEY (COUPON_ID) 
  REFERENCES WEBSITE_COUPONS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_COUPON_EXCLUDED_PRODUCT_CATEGORIES ADD (
  CONSTRAINT FK_COUPON_EXCLUDED_PRODUCT_CATEGORY 
  FOREIGN KEY (COUPON_ID) 
  REFERENCES WEBSITE_COUPONS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_COUPON_EXCLUDED_PRODUCT_IDS ADD (
  CONSTRAINT FK_COUPON_EXCLUDED_PRODUCT 
  FOREIGN KEY (COUPON_ID) 
  REFERENCES WEBSITE_COUPONS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_COUPON_PRODUCT_CATEGORIES ADD (
  CONSTRAINT FK_COUPON_PRODUCT_CATEGORY 
  FOREIGN KEY (COUPON_ID) 
  REFERENCES WEBSITE_COUPONS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_COUPON_PRODUCT_IDS ADD (
  CONSTRAINT FK_COUPON_PRODUCT 
  FOREIGN KEY (COUPON_ID) 
  REFERENCES WEBSITE_COUPONS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_COUPON_USED_BY ADD (
  CONSTRAINT FK_COUPON_USED_BY 
  FOREIGN KEY (COUPON_ID) 
  REFERENCES WEBSITE_COUPONS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_ORDER_META_DATA ADD (
  CONSTRAINT FK_ORDER_META_DATA 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES WEBSITE_ORDERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_SHIPPING_ADDRESS ADD (
  CONSTRAINT FK_SHIPPING_CUSTOMER 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES WEBSITE_CUSTOMERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_SHIPPING_LINES ADD (
  CONSTRAINT FK_SHIPPING_LINE_ORDER 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES WEBSITE_ORDERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_TAXES ADD (
  CONSTRAINT FK_TAX_ORDER 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES WEBSITE_ORDERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_BILLING_ADDRESS ADD (
  CONSTRAINT FK_BILLING_CUSTOMER 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES WEBSITE_CUSTOMERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_LINE_ITEMS ADD (
  CONSTRAINT FK_LINE_ITEM_ORDER 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES WEBSITE_ORDERS (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_PRODUCTS ADD (
  CONSTRAINT FK_PRODUCT_CATEGORY 
  FOREIGN KEY (ID) 
  REFERENCES WEBSITE_PRODUCT_CATEGORIES (ID)
  DISABLE NOVALIDATE);

ALTER TABLE WEBSITE_PRODUCT_IMAGES ADD (
  CONSTRAINT FK_IMAGE_PRODUCT 
  FOREIGN KEY (PRODUCT_ID) 
  REFERENCES WEBSITE_PRODUCTS (ID)
  DISABLE NOVALIDATE);



DROP TABLE STR_ITEM_CATEGORY CASCADE CONSTRAINTS;

CREATE TABLE STR_ITEM_CATEGORY
(
  CAT_ID       NUMBER                           NOT NULL,
  CAT_NAME_EN  VARCHAR2(500 BYTE)               NOT NULL,
  CAT_NAME_AR  VARCHAR2(500 BYTE)               NOT NULL,
  ENTER_BY     VARCHAR2(50 BYTE),
  ENTER_DATE   DATE,
  UPDATE_BY    VARCHAR2(50 BYTE),
  UPDATE_DATE  DATE,
  COM_ID       NUMBER,
  STATUS       VARCHAR2(2 BYTE),
  CAT_CODE     VARCHAR2(50 BYTE)
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


DROP TABLE STR_ITEM_UNIT CASCADE CONSTRAINTS;

CREATE TABLE STR_ITEM_UNIT
(
  UNIT_ID       NUMBER                          NOT NULL,
  UNIT_NAME_AR  VARCHAR2(100 BYTE)              NOT NULL,
  UNIT_NAME_EN  VARCHAR2(100 BYTE)              NOT NULL,
  STATUS        VARCHAR2(2 BYTE),
  ENTER_BY      VARCHAR2(30 BYTE),
  ENTER_DATE    DATE,
  UPDATE_BY     VARCHAR2(30 BYTE),
  UPDATE_DATE   DATE,
  COM_ID        NUMBER,
  UNIT_CODE     VARCHAR2(100 BYTE),
  UOM_CAT_ID    NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;



DROP TABLE STR_ITEM_BRAND CASCADE CONSTRAINTS;

CREATE TABLE STR_ITEM_BRAND
(
  ID            NUMBER                          NOT NULL,
  NAME_AR       VARCHAR2(500 BYTE)              NOT NULL,
  NAME_EN       VARCHAR2(500 BYTE)              NOT NULL,
  STATUS        VARCHAR2(2 BYTE),
  COM_ID        NUMBER,
  REMARKS       VARCHAR2(4000 BYTE),
  CREATED_BY    VARCHAR2(50 BYTE),
  CREATED_DATE  DATE,
  UPDATED_BY    VARCHAR2(50 BYTE),
  UPDATED_DATE  DATE
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE OR REPLACE TRIGGER "INS_STR_ITEM_BRAND" BEFORE INSERT ON STR_ITEM_BRAND FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT NVL(MAX(ID),0)  + 1
    INTO :NEW.ID
    FROM STR_ITEM_BRAND;
    END IF;
END;




DROP TABLE DUMMY CASCADE CONSTRAINTS;

CREATE TABLE DUMMY
(
  ID            NUMBER,
  VAL1          VARCHAR2(1000 BYTE),
  VAL2          VARCHAR2(1000 BYTE),
  VAL3          VARCHAR2(1000 BYTE),
  VAL4          VARCHAR2(1000 BYTE),
  CLOB_VAL      CLOB,
  CLOB_VAL2     CLOB,
  CLOB_VAL3     CLOB,
  CREATED_ON    DATE                            DEFAULT SYSDATE,
  REFERENCE_NO  NUMBER
)
LOB (CLOB_VAL) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (CLOB_VAL2) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (CLOB_VAL3) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;



DROP TABLE SM_SALE_INVOICE_MASTER CASCADE CONSTRAINTS;

CREATE TABLE SM_SALE_INVOICE_MASTER
(
  INVOICE_ID                     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 367 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  INVOICE_NO                     VARCHAR2(500 BYTE),
  TRANS_DATE                     DATE           DEFAULT SYSDATE,
  CUSTOMER_ID                    NUMBER,
  DELIVERY_CHALLAN_ID            NUMBER,
  GATEPASS_ID                    NUMBER,
  TOTAL_AMOUNT                   NUMBER,
  TAX_AMOUNT                     NUMBER,
  NET_AMOUNT                     NUMBER,
  CURRENCY_ID                    NUMBER,
  EXCHANGE_RATE                  NUMBER         DEFAULT 1,
  EXCHANGE_DATE                  DATE,
  VOUCHER_NO                     VARCHAR2(500 BYTE),
  LC_COA_ID                      NUMBER,
  LC_EXCHANGE_RATE               NUMBER,
  LC_ENTERED_AMOUNT              NUMBER,
  LC_AMOUNT                      NUMBER,
  LC_BANK_ID                     NUMBER,
  LC_VOUCHER_NO                  VARCHAR2(500 BYTE),
  LC_REMARKS                     VARCHAR2(500 BYTE),
  EXPENCE_AMOUNT                 NUMBER,
  STORE_ID                       NUMBER,
  INVOICE_TYPE_ID                NUMBER,
  COMMISSION_VOUCHER_ID          NUMBER,
  SALE_PERSON_ID                 NUMBER,
  STATUS_ID                      NUMBER,
  REMARKS                        VARCHAR2(500 BYTE),
  COMPANY_ID                     NUMBER,
  BRANCH_ID                      NUMBER,
  CREATED_BY                     NUMBER,
  CREATION_DATE                  DATE           DEFAULT SYSDATE,
  LAST_UPDATED_BY                NUMBER,
  LAST_UPDATE_DATE               DATE,
  APPROVED_BY                    NUMBER,
  APPROVAL_DATE                  DATE,
  TAX_ID                         NUMBER,
  TAX_PERCENTAGE                 NUMBER,
  BANK_ID                        NUMBER,
  VOUCHER_TYPE_ID                NUMBER,
  COST_CENTER_ID                 NUMBER,
  INVOICE_PRINTED                CHAR(1 BYTE)   DEFAULT 'N',
  INVOICE_PRINT_DATE             DATE,
  INVOICE_PRINTED_BY             NUMBER,
  VOUCHER_TYPE_CODE              VARCHAR2(500 BYTE),
  SALES_DATE                     DATE,
  PAYMENTS_TYPE                  NUMBER,
  DELIVERY_METHOD                NUMBER,
  DELIVERY_CHARGES               NUMBER,
  ORDER_REF_NO                   VARCHAR2(100 BYTE),
  TRACKING_NUMBER                VARCHAR2(100 BYTE),
  EVENT_SALES_FLAG               NUMBER         DEFAULT 0,
  EVENT_CODE                     VARCHAR2(30 BYTE),
  EVENT_SLOT_NO                  NUMBER,
  EVENT_ID                       NUMBER,
  EVENT_MANAGER_ID               NUMBER,
  WEBSITE_SALES_FLAG             NUMBER         DEFAULT 0,
  WEBSITE_ORDER_CONTACT          VARCHAR2(100 BYTE),
  WEBSITE_ORDER_NOTES            VARCHAR2(4000 BYTE),
  WEBSITE_ORDER_COUPON_CODE      VARCHAR2(100 BYTE),
  WEBSITE_ORDER_COUPON_DISCOUNT  NUMBER,
  WEBSITE_ORDER_SHIPPING_METHOD  VARCHAR2(100 BYTE),
  WEBSITE_ORDER_SHIPPING_DAYS    VARCHAR2(100 BYTE),
  POSTED_TO_TAX                  NUMBER(1)      DEFAULT 0,
  INVOICE_TYPE_CODE              VARCHAR2(100 BYTE),
  PAYMENT_CODE                   NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON COLUMN SM_SALE_INVOICE_MASTER.POSTED_TO_TAX IS 'default value 0, after verify phase2 intrigation value 1';

COMMENT ON COLUMN SM_SALE_INVOICE_MASTER.INVOICE_TYPE_CODE IS 'b2b ''0100000''  -   b2c    ''0200000''';

COMMENT ON COLUMN SM_SALE_INVOICE_MASTER.PAYMENT_CODE IS 'Cash   10, Credit 30, Payment to bank account 42, Bank card 48';


ALTER TABLE SM_SALE_INVOICE_MASTER ADD (
  PRIMARY KEY
  (INVOICE_ID)
  USING INDEX
    TABLESPACE APEX_23321186687074315
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);


DROP SEQUENCE ISEQ$$_140151;

-- Sequence ISEQ$$_140151 is created automatically by Oracle for use with an Identity column


--  There is no statement for index SYS_C0034863.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER "INS_INVOICE_MASTER" 
  BEFORE INSERT ON SM_SALE_INVOICE_MASTER
  FOR EACH ROW
BEGIN
  IF :NEW.INVOICE_ID IS NULL THEN
    SELECT NVL(MAX(INVOICE_ID), 0) + 1
      INTO :NEW.INVOICE_ID
      FROM SM_SALE_INVOICE_MASTER A;
  END IF;
END;


DROP TABLE SM_SALE_INVOICE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE SM_SALE_INVOICE_DETAIL
(
  INVOICE_DETAIL_ID         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 461 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  INVOICE_ID                NUMBER,
  SALE_ORDER_ID             NUMBER,
  SALE_ORDER_ITEM_ID        NUMBER,
  ITEM_ID                   NUMBER,
  UOM_ID                    NUMBER,
  QTY                       NUMBER,
  RATE                      NUMBER,
  AMOUNT                    NUMBER,
  TAX_ID                    NUMBER,
  TAX_PERCENT               NUMBER,
  TAX_AMOUNT                NUMBER,
  LC_QTY                    NUMBER,
  LC_RATE                   NUMBER,
  LC_AMOUNT                 NUMBER,
  EXCISE_DUTY               NUMBER,
  ITEM_SIZE                 NUMBER,
  CGS                       NUMBER,
  RETURNED_QTY              NUMBER,
  EXCESS_QTY                NUMBER,
  TOTAL_WEIGHT              NUMBER,
  REMARKS                   VARCHAR2(500 BYTE),
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE                DEFAULT SYSDATE,
  LAST_UPDATED_BY           NUMBER,
  LAST_UPDATE_DATE          DATE,
  TOTAL_VALUE               NUMBER,
  DELIVERY_ORDER_ID         NUMBER,
  DELIVERY_ORDER_ITEM_ID    NUMBER,
  DELIVERY_CHALLAN_ID       NUMBER,
  DELIVERY_CHALLAN_ITEM_ID  NUMBER,
  DISCOUNT_AMOUNT           NUMBER,
  DISCOUNT_PERCENTAGE       NUMBER,
  DISCOUNT_TYPE             VARCHAR2(100 BYTE),
  EVENT_SALES_FLAG          NUMBER              DEFAULT 0,
  EVENT_CODE                VARCHAR2(30 BYTE),
  EVENT_SLOT_NO             NUMBER,
  EVENT_ID                  NUMBER
)
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX PK_SM_SALE_INVOICE_DETAIL ON SM_SALE_INVOICE_DETAIL
(INVOICE_DETAIL_ID)
LOGGING
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SM_SALE_INVOICE_DETAIL ADD (
  CONSTRAINT PK_SM_SALE_INVOICE_DETAIL
  PRIMARY KEY
  (INVOICE_DETAIL_ID)
  USING INDEX PK_SM_SALE_INVOICE_DETAIL
  ENABLE VALIDATE);


DROP SEQUENCE ISEQ$$_140149;

-- Sequence ISEQ$$_140149 is created automatically by Oracle for use with an Identity column


CREATE OR REPLACE TRIGGER "INS_SM_SALE_INVOICE_DETAIL" BEFORE INSERT ON SM_SALE_INVOICE_DETAIL FOR EACH ROW
BEGIN
  IF :NEW.INVOICE_DETAIL_ID IS NULL THEN
    SELECT NVL(MAX(INVOICE_DETAIL_ID),0) + 1
    INTO :NEW.INVOICE_DETAIL_ID
    FROM SM_SALE_INVOICE_DETAIL;
    END IF;
    END;





DROP TABLE STR_SETUP_ITEM_DTL CASCADE CONSTRAINTS;

CREATE TABLE STR_SETUP_ITEM_DTL
(
  ITEM_ID                        NUMBER         NOT NULL,
  CAT_ID                         NUMBER,
  ITEM_NAME_AR                   VARCHAR2(500 BYTE),
  ITEM_NAME_EN                   VARCHAR2(500 BYTE) NOT NULL,
  ENTER_BY                       VARCHAR2(50 BYTE),
  ENTER_DATE                     DATE,
  UPDATE_BY                      VARCHAR2(50 BYTE),
  UPDATE_DATE                    DATE,
  COM_ID                         NUMBER,
  STATUS                         VARCHAR2(1 BYTE) DEFAULT 'Y',
  UOM                            VARCHAR2(10 BYTE),
  UNIT_PRICE                     NUMBER,
  COST_PRICE                     NUMBER,
  TAX_TYPE_ID                    NUMBER,
  MAX_UNIT                       NUMBER,
  MIN_UNIT                       NUMBER,
  COST_CENTRE_ID                 NUMBER,
  POLICY_FOR_DISPENSING_ITEM_ID  NUMBER,
  ITEM_TYPE                      VARCHAR2(10 BYTE),
  INVENTORY_TYPE                 VARCHAR2(500 BYTE),
  ITEM_BARCODE                   VARCHAR2(100 BYTE),
  ITEM_CODE                      VARCHAR2(50 BYTE),
  BRAND_ID                       NUMBER,
  VENDOR_BARCODE                 VARCHAR2(100 BYTE),
  ITEM_IMAGE                     BLOB,
  ITEM_IMAGE_FILE_NAME           VARCHAR2(4000 BYTE),
  ITEM_IMAGE_MIMETYPE            VARCHAR2(4000 BYTE),
  SALES                          VARCHAR2(1000 BYTE),
  DAMAGE                         VARCHAR2(1000 BYTE),
  PROFIT_AMOUNT                  NUMBER,
  RATE_PROFITE                   NUMBER,
  ACCOUNT                        VARCHAR2(500 BYTE),
  ACCUMULATED_DEPRECIATION       NUMBER(38),
  ASSET_ACCOUNT                  VARCHAR2(500 BYTE),
  COGS_ACCOUNT                   VARCHAR2(500 BYTE),
  DISCOUNT_PERCENTAGE            VARCHAR2(500 BYTE),
  EXPIRY_DATE                    VARCHAR2(500 BYTE),
  MPN                            VARCHAR2(500 BYTE),
  PREFERRED_VENDOR               VARCHAR2(500 BYTE),
  PURCHASE_DESCRIPTION           VARCHAR2(500 BYTE),
  QUANTITY_ON_HAND               NUMBER(38),
  SALES_TAX_CODE                 VARCHAR2(500 BYTE),
  TAX_AGENCY                     VARCHAR2(500 BYTE),
  SKU_SIZE                       VARCHAR2(500 BYTE),
  COLOR                          VARCHAR2(500 BYTE),
  SKU_LENGTH                     VARCHAR2(500 BYTE),
  WIDTH                          VARCHAR2(500 BYTE),
  HEIGHT                         VARCHAR2(500 BYTE),
  DIAMETER                       VARCHAR2(500 BYTE),
  WEIGHT                         VARCHAR2(500 BYTE),
  DAMAGE_QTY                     NUMBER,
  TOTAL_QTY                      NUMBER,
  REMARKS                        VARCHAR2(500 BYTE),
  SKU                            VARCHAR2(500 BYTE),
  PRODUCT_IMAGE_NAME             VARCHAR2(1000 BYTE),
  PARENT_SKU                     VARCHAR2(500 BYTE),
  BRAND_NAME                     VARCHAR2(100 BYTE),
  CATEGORY_NAME                  VARCHAR2(100 BYTE) DEFAULT 0
)
LOB (ITEM_IMAGE) STORE AS SECUREFILE (
  TABLESPACE  APEX_23321186687074315
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE APEX_23321186687074315
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


ALTER TABLE STR_SETUP_ITEM_DTL ADD (
  CHECK ("CAT_ID" IS NOT NULL)
  DISABLE NOVALIDATE
,  CHECK ("ITEM_NAME_AR" IS NOT NULL)
  DISABLE NOVALIDATE);


DROP SEQUENCE STR_SETUP_ITEM_DTL_SEQ;

CREATE SEQUENCE STR_SETUP_ITEM_DTL_SEQ
  START WITH 10000001
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE TRIGGER trg_generate_item_id
BEFORE INSERT ON STR_SETUP_ITEM_DTL
FOR EACH ROW
BEGIN
  IF :NEW.ITEM_ID IS NULL THEN
    -- Assign the next value from the sequence to ITEM_ID
    SELECT str_setup_item_dtl_seq.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL;
  END IF;
END;
